# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c36b09e04f58e54fef2168c10dba03b0de8ca1506f8d2d30e2aa40b8bd58140215440721910baa4a93bd8a06e57a2d526143dadf87d916cf7b76d991b52ce9aa

test:
  secret_key_base: 2857ba0a86dba341678c9998dd40a0f9c8147c6acc7fe01010a65fb5f6d2130b7a0037b38991628b8c8b9738c6b815f1c7755303c9160978aefae25f417c5a50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
